### ISSUE TITLE
shipit_uplift: CORS issues

### ISSUE THREAD

**Issue by armenzg** [mozilla-releng/services#639]
I thought this was fixed, however, I'm getting this:
> Fetch API cannot load https://uplift.shipit.staging.mozilla-releng.net/coverage/changeset_summary/bc56729898954e32d3a3731d03d178ed78924c33. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. The response had HTTP status code 503. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

CC: @marco-c 

This is the code fetching it:
```javascript
export const ccovBackend = 'https://uplift.shipit.staging.mozilla-releng.net';
const jsonHeaders = {
  Accept: 'application/json'
};
export const getChangesetCoverageSummary = changeset =>
  fetch(`${ccovBackend}/coverage/changeset_summary/${changeset}`, { jsonHeaders });
```

**Comment by marco-c** [comment]
The commit which fixed the CORS issue (https://github.com/mozilla-releng/services/pull/599) hadn't landed on master yet and was removed from staging (because of a master -> staging push).
The commit landed yesterday on master, so it will not be removed anymore.

I will push it manually to staging now.

**Comment by marco-c** [comment]
Effectively duplicate of https://github.com/mozilla-releng/services/issues/598.

**Comment by armenzg** [comment]
ah! That explains it.
Thank you Marco. I will try again.

**Comment by armenzg** [comment]
I'm still hitting it even after this completed:
https://tools.taskcluster.net/groups/Y-e0IsH9QsOYBPzlGMbF0A

I also tried to load it manually:
https://uplift.shipit.staging.mozilla-releng.net/coverage/changeset_summary/e6b3498a39b94616ba36798fe0b71a3090b1b14c
and I get this:
> Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

Is this cached?

**Comment by marco-c** [comment]
So, it looks like the request is taking a long time and it's getting killed by heroku (just like #611).
This should be fixed when we fix https://github.com/mozilla-releng/services/issues/632.

**Comment by armenzg** [comment]
I'm doing one fetch at a time and I still get issues:
https://uplift.shipit.staging.mozilla-releng.net/coverage/changeset_summary/e6b3498a39b94616ba36798fe0b71a3090b1b14c

Did you see anything in the logs that could show what is happening?

**Comment by armenzg** [comment]
I see:
> Can't load codecov.io report

**Comment by marco-c** [comment]
> I'm doing one fetch at a time and I still get issues:
https://uplift.shipit.staging.mozilla-releng.net/coverage/changeset_summary/e6b3498a39b94616ba36798fe0b71a3090b1b14c

> Did you see anything in the logs that could show what is happening?

The issue with this particular changeset is that it is huge (it's a merge commit containing 130 files modified, maybe we can skip merge commits in the frontend?), so until we fix #632 it will always timeout.
So, I would expect the issues now to be limited to the large changesets. Are you seeing them on normal-sized changesets too?
